
const mongoose = require("mongoose");
const appointmentIdPlugin = require("../Plugins/telicallings_model_for_setting_appointment_id_plugin");
const createLogsAutomaticallyOnUpdatePlugin = require("../Plugins/telecallings_model_for_update_logs_plugin");



const telecallingSchema = new mongoose.Schema(
    {
        // Auto-generated by plugin
        appointmentId: { type: String, trim: true, index: true, unique: true },

        // REQUIRED business fields (keep required)
        carRegistrationNumber: { type: String, required: true, trim: true },
        yearOfRegistration: { type: String, required: true, trim: true },
        ownerName: { type: String, required: true, trim: true },
        ownershipSerialNumber: { type: Number, required: true },
        make: { type: String, required: true, trim: true },
        model: { type: String, required: true, trim: true },
        variant: { type: String, required: true, trim: true },

        // Ensure field exists using defaults
        timeStamp: { type: Date, default: () => new Date() },

        emailAddress: { type: String, trim: true, lowercase: true, default: "" },
        appointmentSource: { type: String, trim: true, default: "" },
        vehicleStatus: { type: String, trim: true, default: "" },
        zipCode: { type: String, trim: true, default: "" },
        customerContactNumber: { type: String, trim: true, default: "" },
        city: { type: String, trim: true, default: "" },

        yearOfManufacture: { type: String, trim: true, default: "" },

        allocatedTo: { type: String, trim: true, default: "" },
        inspectionStatus: { type: String, trim: true, default: "Pending" },
        approvalStatus: { type: String, trim: true, default: "Pending" },
        priority: { type: String, trim: true, default: "Medium" },
        ncdUcdName: { type: String, trim: true, default: "" },
        repName: { type: String, trim: true, default: "" },
        repContact: { type: String, trim: true, default: "" },
        bankSource: { type: String, trim: true, default: "" },
        referenceName: { type: String, trim: true, default: "" },
        remarks: { type: String, trim: true, default: "" },
        createdBy: { type: String, trim: true, default: "" },

        // optional-but-present always
        odometerReadingInKms: { type: Number, default: null },
        additionalNotes: { type: String, trim: true, default: "" },
        carImages: { type: [String], default: [] },

        inspectionDateTime: { type: Date, default: null },
        inspectionAddress: { type: String, trim: true, default: "" },
        inspectionEngineerNumber: { type: String, trim: true, default: "" },
        addedBy: {
            type: String, enum: [
                "Customer",
                "Telecaller",
                "Otobix Website",
                "Dealer (Seller)",
                "QC"
            ], trim: true, default: "Telecaller"
        },
        inspectionRequestedThrough: { type: String, trim: true, default: "Sell My Car" },
        contactPerson: { type: String, trim: true, default: ''}, // only for (Self inspected car accept offer)
        logs: [
            {
                changedAt: { type: Date, default: Date.now },
                changedBy: { type: String, trim: true, default: "" }, // user id/name
                source: { type: String, trim: true, default: "" },    // API / panel / etc
                changes: [
                    {
                        field: { type: String, trim: true },
                        from: { type: mongoose.Schema.Types.Mixed },
                        to: { type: mongoose.Schema.Types.Mixed },
                    },
                ],
            },
        ],


    },
    {
        timestamps: true,
        strict: true, // prevents saving unknown fields
    }
);

// plugin ONLY for appointmentId
telecallingSchema.plugin(appointmentIdPlugin, {
    field: "appointmentId",
    counterPrefix: "appointmentId",
});

// plugin ONLY for audit update logs
telecallingSchema.plugin(createLogsAutomaticallyOnUpdatePlugin, {
    logsPath: "logs",
    ignore: ["appointmentId", "logs", "__v", "createdAt", "updatedAt", "timeStamp"],
    metaOptionKey: "audit",
});

module.exports = mongoose.model("Telecallings", telecallingSchema, "telecallings");


